### ISSUE TITLE
latest primer3 does not work

### ISSUE THREAD

**Issue by bwlang** [pseudogene/lava-dna#3]
seems that the thermo params file has now been embedded.

**Comment by pseudogene** [comment]
Thanks for that. I will edit the code to reflect that, as soon I as I can.

**Comment by bwlang** [comment]
I have a fox in my fork... will send a PR soon

Sent from my phone.  Please excuse any typos/autocorrect nonsense.

On Apr 12, 2020, at 5:07 AM, Michaël Bekaert <notifications@github.com> wrote:

﻿
EXTERNAL SENDER


Thanks for that. I will edit the code to reflect that, as soon I as I can.
